# Generated by Django 5.2 on 2025-04-13 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamerachi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Post listi', 'verbose_name_plural': '4. Post listi'},
        ),
        migrations.AlterModelOptions(
            name='videosposts',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videolar'},
        ),
        migrations.RenameField(
            model_name='imageposts',
            old_name='posts',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='kamerachi.category'),
        ),
        migrations.AlterField(
            model_name='videosposts',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='kamerachi.posts'),
        ),
    ]
