# Generated by Django 5.2 on 2025-04-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kamerachi', '0002_alter_posts_options_alter_videosposts_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideosPosts',
        ),
    ]
