# Generated by Django 5.2 on 2025-04-15 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamerachi', '0003_delete_videosposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='kamerachi.category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
