# Generated by Django 5.2 on 2025-04-16 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamerachi', '0004_alter_products_category_delete_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Post listi', 'verbose_name_plural': '3. Post listi'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Kamera listi', 'verbose_name_plural': '2. Kameralar listi'},
        ),
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
